tf_init:
	cd terraform && terraform init -upgrade

tf_validate:
	cd terraform && terraform validate

tf_plan:
	cd terraform && terraform plan

tf_apply:
	cd terraform && terraform apply -auto-approve

tf_destroy:
	cd terraform && terraform destroy -auto-approve
